import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-medicaid-supplemental-payment-reconciliation",
  "engine": "recovery",
  "title": "Medicaid Supplemental Payment Reconciliation",
  "shortTitle": "Medicaid Supplemental Payment Reconciliation",
  "tagline": "Reconcile complex Medicaid supplemental pools and recover omitted or misallocated provider payments.",
  "industry": "Medicaid Provider Finance",
  "buyer": "Hospitals, states, and provider associations",
  "uiPort": 4691,
  "apiPort": 5691,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Medicaid Supplemental Payment Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements in one accountable workflow. Reconcile complex Medicaid supplemental pools and recover omitted or misallocated provider payments.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Medicaid Supplemental Payment Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("program-authority-library","MSP01","Program authority library","Execute program authority library using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed program authority library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Program authority library Reference","text","MSP01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("provider-eligibility-registry","MSP02","Provider eligibility registry","Execute provider eligibility registry using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed provider eligibility registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Provider eligibility registry Reference","text","MSP02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("base-claim-ingestion","MSP03","Base claim ingestion","Execute base claim ingestion using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed base claim ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Base claim ingestion Reference","text","MSP03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("uncompensated-care-calculation","MSP04","Uncompensated care calculation","Execute uncompensated care calculation using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed uncompensated care calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Uncompensated care calculation Reference","text","MSP04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("upper-payment-limit-control","MSP05","Upper payment limit control","Execute upper payment limit control using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed upper payment limit control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Upper payment limit control Reference","text","MSP05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("dsh-limit-calculation","MSP06","DSH limit calculation","Execute dsh limit calculation using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed dsh limit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","DSH limit calculation Reference","text","MSP06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("directed-payment-methodology","MSP07","Directed payment methodology","Execute directed payment methodology using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed directed payment methodology decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Directed payment methodology Reference","text","MSP07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("quality-pool-scoring","MSP08","Quality pool scoring","Execute quality pool scoring using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed quality pool scoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Quality pool scoring Reference","text","MSP08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("provider-tax-interaction","MSP09","Provider tax interaction","Execute provider tax interaction using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed provider tax interaction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Provider tax interaction Reference","text","MSP09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("intergovernmental-transfer","MSP10","Intergovernmental transfer","Execute intergovernmental transfer using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed intergovernmental transfer decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Intergovernmental transfer Reference","text","MSP10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("pool-allocation-calculation","MSP11","Pool allocation calculation","Execute pool allocation calculation using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed pool allocation calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Pool allocation calculation Reference","text","MSP11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("state-payment-file-matching","MSP12","State payment file matching","Execute state payment file matching using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed state payment file matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","State payment file matching Reference","text","MSP12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("provider-dispute-workflow","MSP13","Provider dispute workflow","Execute provider dispute workflow using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed provider dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Provider dispute workflow Reference","text","MSP13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("cash-reconciliation","MSP14","Cash reconciliation","Execute cash reconciliation using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Cash reconciliation Reference","text","MSP14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]}),
feature("program-provider-analytics","MSP15","Program provider analytics","Execute program provider analytics using state plan amendments, provider eligibility, base claims, uncompensated care, upper payment limits, quality pools, directed payments, assessments, distributions, and settlements.","Produce a governed program provider analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Provider / Payment Pool","text","Provider / Payment Pool · Standard Case"],["caseReference","Program provider analytics Reference","text","MSP15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1167500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1412675],["domainDriver","Payment Pool","select","DSH",["DSH","Directed payment","UPL supplemental"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program authority library case","Provider eligibility registry case","Base claim ingestion case","Uncompensated care calculation case","Upper payment limit control case"]})
]);
